import { Goal, Task, ScheduleBlock, FocusSession, UserPreferences } from '../types';

export const DEFAULT_PREFERENCES: UserPreferences = {
  workStartTime: '09:00',
  workEndTime: '18:00',
  focusDurationMinutes: 45,
  shortBreakMinutes: 10,
  longBreakMinutes: 20,
  sessionsBeforeLongBreak: 3,
  dailyWorkloadLimitHours: 7,
  soundEnabled: true,
  ambientSound: 'none',
  theme: 'dark',
  autoScheduleOnAccept: true,
  userName: 'Alex Rivers',
};

const today = new Date().toISOString().split('T')[0];

export const SAMPLE_GOALS: Goal[] = [
  {
    id: 'goal_hackathon_demo',
    title: '🏆 Launch Hackathon AI Product MVP',
    description: 'Complete high-impact full-stack AI execution agent, live demo pitch, and deploy production build in 48 hours.',
    category: 'Product & Engineering',
    deadline: today,
    targetHours: 12,
    status: 'active',
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    isSample: true,
    aiGenerated: true,
  },
  {
    id: 'goal_deep_learning',
    title: '🧠 Deep Learning & LLM Systems Exam Prep',
    description: 'Master Transformer architectures, attention mechanisms, quantization, and KV caching benchmarks.',
    category: 'Academics',
    deadline: new Date(Date.now() + 86400000 * 3).toISOString().split('T')[0],
    targetHours: 10,
    status: 'active',
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    isSample: true,
    aiGenerated: true,
  },
];

export const SAMPLE_TASKS: Task[] = [
  {
    id: 'task_1',
    goalId: 'goal_hackathon_demo',
    title: 'Implement Multi-Factor Prioritization Scoring Engine',
    description: 'Write mathematical urgency, importance, and DAG dependency evaluation algorithm with natural language breakdown.',
    priority: 'critical',
    estimatedMinutes: 45,
    actualMinutes: 45,
    deadline: today,
    dependencies: [],
    status: 'completed',
    subtasks: [
      { id: 'st_1_1', taskId: 'task_1', title: 'Define weights for deadline urgency', completed: true, estimatedMinutes: 15 },
      { id: 'st_1_2', taskId: 'task_1', title: 'Implement DAG dependency penalty', completed: true, estimatedMinutes: 15 },
      { id: 'st_1_3', taskId: 'task_1', title: 'Add natural language explanation generator', completed: true, estimatedMinutes: 15 },
    ],
    executionOrder: 1,
    recommendedReason: 'Foundational engine required for schedule generation.',
    priorityScore: 98,
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    completedAt: new Date(Date.now() - 3600000 * 2).toISOString(),
    isSample: true,
  },
  {
    id: 'task_2',
    goalId: 'goal_hackathon_demo',
    title: 'Build Immersive Focus Mode with Ambient Sound Synthesis',
    description: 'Full-screen distraction-free timer with Web Audio binaural beats and subtask checklists.',
    priority: 'high',
    estimatedMinutes: 50,
    actualMinutes: 25,
    deadline: today,
    dependencies: ['task_1'],
    status: 'in-progress',
    subtasks: [
      { id: 'st_2_1', taskId: 'task_2', title: 'Setup delta drift-proof countdown timer', completed: true, estimatedMinutes: 20 },
      { id: 'st_2_2', taskId: 'task_2', title: 'Integrate Web Audio API synthesizers', completed: false, estimatedMinutes: 15 },
      { id: 'st_2_3', taskId: 'task_2', title: 'Add completion celebration trigger', completed: false, estimatedMinutes: 15 },
    ],
    executionOrder: 2,
    recommendedReason: 'Top ongoing focus task. Complete ambient generator for maximum demo impact.',
    priorityScore: 88,
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    isSample: true,
  },
  {
    id: 'task_3',
    goalId: 'goal_hackathon_demo',
    title: 'Design Interactive Schedule & Timeline Visualizer',
    description: 'Create time-blocked view with conflict alerts, active time indicators, and quick reschedule hooks.',
    priority: 'high',
    estimatedMinutes: 40,
    actualMinutes: 0,
    deadline: today,
    dependencies: ['task_1'],
    status: 'todo',
    subtasks: [
      { id: 'st_3_1', taskId: 'task_3', title: 'Render chronological timeline with badges', completed: false, estimatedMinutes: 20 },
      { id: 'st_3_2', taskId: 'task_3', title: 'Show real-time conflict banners', completed: false, estimatedMinutes: 20 },
    ],
    executionOrder: 3,
    recommendedReason: 'Critical UI milestone for visual schedule walkthrough.',
    priorityScore: 78,
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    isSample: true,
  },
  {
    id: 'task_4',
    goalId: 'goal_hackathon_demo',
    title: 'Setup Adaptive Rescheduling & Delay Recovery Flow',
    description: 'Recalculate remaining schedule blocks automatically when a task runs late or priority shifts.',
    priority: 'medium',
    estimatedMinutes: 35,
    actualMinutes: 0,
    deadline: today,
    dependencies: ['task_3'],
    status: 'todo',
    subtasks: [
      { id: 'st_4_1', taskId: 'task_4', title: 'Calculate time delta shift from current time', completed: false, estimatedMinutes: 15 },
      { id: 'st_4_2', taskId: 'task_4', title: 'Generate visual diff of moved blocks', completed: false, estimatedMinutes: 20 },
    ],
    executionOrder: 4,
    recommendedReason: 'Key intelligence feature requested in hackathon rubric.',
    priorityScore: 62,
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    isSample: true,
  },
  {
    id: 'task_5',
    goalId: 'goal_deep_learning',
    title: 'Review Attention Mechanism & KV Caching Architecture',
    description: 'Summarize Multi-Head, Grouped-Query, and FlashAttention 2 memory bandwidth trade-offs.',
    priority: 'medium',
    estimatedMinutes: 45,
    actualMinutes: 0,
    deadline: new Date(Date.now() + 86400000 * 2).toISOString().split('T')[0],
    dependencies: [],
    status: 'todo',
    subtasks: [
      { id: 'st_5_1', taskId: 'task_5', title: 'Diagram MHA vs GQA key-value tensor shapes', completed: false, estimatedMinutes: 20 },
      { id: 'st_5_2', taskId: 'task_5', title: 'Calculate KV cache RAM requirements for 70B model', completed: false, estimatedMinutes: 25 },
    ],
    executionOrder: 5,
    recommendedReason: 'Moderate urgency; scheduled for afternoon focus block.',
    priorityScore: 48,
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    isSample: true,
  },
];

export const SAMPLE_SCHEDULE_BLOCKS: ScheduleBlock[] = [
  {
    id: 'sb_1',
    taskId: 'task_1',
    title: 'Implement Multi-Factor Prioritization Scoring Engine',
    startTime: '09:00',
    endTime: '09:45',
    type: 'focus',
    status: 'completed',
    date: today,
    priority: 'critical',
    actualMinutes: 45,
    isSample: true,
  },
  {
    id: 'sb_break_1',
    title: '⚡ Micro Break & Hydration',
    startTime: '09:45',
    endTime: '09:55',
    type: 'break',
    status: 'completed',
    date: today,
    isSample: true,
  },
  {
    id: 'sb_2',
    taskId: 'task_2',
    title: 'Build Immersive Focus Mode with Ambient Sound Synthesis',
    startTime: '09:55',
    endTime: '10:45',
    type: 'focus',
    status: 'in-progress',
    date: today,
    priority: 'high',
    actualMinutes: 25,
    isSample: true,
  },
  {
    id: 'sb_break_2',
    title: '☕ Deep Refresh Break',
    startTime: '10:45',
    endTime: '11:05',
    type: 'break',
    status: 'planned',
    date: today,
    isSample: true,
  },
  {
    id: 'sb_3',
    taskId: 'task_3',
    title: 'Design Interactive Schedule & Timeline Visualizer',
    startTime: '11:05',
    endTime: '11:45',
    type: 'focus',
    status: 'planned',
    date: today,
    priority: 'high',
    isSample: true,
  },
  {
    id: 'sb_4',
    taskId: 'task_4',
    title: 'Setup Adaptive Rescheduling & Delay Recovery Flow',
    startTime: '11:45',
    endTime: '12:20',
    type: 'focus',
    status: 'planned',
    date: today,
    priority: 'medium',
    isSample: true,
  },
];

export const SAMPLE_FOCUS_SESSIONS: FocusSession[] = [
  {
    id: 'fs_1',
    taskId: 'task_1',
    taskTitle: 'Implement Multi-Factor Prioritization Scoring Engine',
    targetMinutes: 45,
    actualMinutes: 45,
    startTime: `${today}T09:00:00Z`,
    endTime: `${today}T09:45:00Z`,
    status: 'completed',
    notes: 'Completed scoring algorithms and edge cases seamlessly.',
    date: today,
    subtasksCompleted: 3,
  },
  {
    id: 'fs_past_1',
    taskTitle: 'System Architecture & Data Access Layer Setup',
    targetMinutes: 50,
    actualMinutes: 50,
    startTime: new Date(Date.now() - 86400000).toISOString(),
    endTime: new Date(Date.now() - 86400000 + 3000000).toISOString(),
    status: 'completed',
    notes: 'Configured robust types and localStorage event bus.',
    date: new Date(Date.now() - 86400000).toISOString().split('T')[0],
    subtasksCompleted: 4,
  },
  {
    id: 'fs_past_2',
    taskTitle: 'Vite & Tailwind Design System Scaffolding',
    targetMinutes: 40,
    actualMinutes: 40,
    startTime: new Date(Date.now() - 86400000 * 2).toISOString(),
    endTime: new Date(Date.now() - 86400000 * 2 + 2400000).toISOString(),
    status: 'completed',
    notes: 'Set up dark palette, glass panels, and typography.',
    date: new Date(Date.now() - 86400000 * 2).toISOString().split('T')[0],
    subtasksCompleted: 2,
  },
];
